/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Pantallas;

import BaseDeDatos.BDOpciones;
import Entidades.Lamina;
import Entidades.Opciones;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author jose
 */
public class D_Opciones extends javax.swing.JDialog {

    /**
     * Creates new form D_Opciones2
     */
    boolean nuevo;
    Opciones opcion_actual=new Opciones() {};
    public D_Opciones(java.awt.Frame parent, boolean modal,Lamina lamina) {
        //bloque la ventana padre de jdialog
        super(parent, modal);
        //varible que se usa para indicar que el es una edición de datos o una inserción
        nuevo=true;
        opcion_actual.setLamina(lamina);
        initComponents();
        CargarBox();

    }
    
    public D_Opciones(java.awt.Frame parent, boolean modal, Opciones opcion,Lamina lamina,boolean estado){
        //bloque la ventana padre de jdialog
        super(parent,modal);
        //varible que se usa para indicar que el es una edición de datos o una inserción
        nuevo=false;
        opcion_actual=opcion;
        opcion_actual.setLamina(lamina);
        initComponents();
        setDefaultCloseOperation(0);
        b_cancelar.setEnabled(estado);
        CargarBox();
        CargarDatos();
    }
    
  
    private void CargarBox(){
        box_1.removeAllItems();
        box_1.addItem("D");
        box_1.addItem("G");
        box_1.addItem("Dd");
        box_2.removeAllItems();
        box_2.addItem("B");
        box_2.addItem("B+");
        box_2.addItem("B-");
        box_2.addItem("C");
        box_2.addItem("F");
        box_2.addItem("F+");
        box_2.addItem("F-");
        box_3.removeAllItems();
        box_3.addItem("M");
        box_3.addItem("Md");
        box_3.addItem("T");
        box_3.addItem("Td");
        box_3.addItem("Pl");
        box_3.addItem("Abstr");
        box_3.addItem("Anat");
        box_3.addItem("Sex");
        box_3.addItem("Geo");
        box_3.addItem("Obj");
        box_3.addItem("Mascara");
        box_3.addItem("Sangre");
        box_3.addItem("Fuego");
        box_3.addItem("Refl");
        box_3.addItem("Simetria");
        box_3.addItem("Pinza");
        box_3.addItem("Arq");
        box_4.removeAllItems();
        box_4.addItem("");
        box_4.addItem("Orig");
        box_4.addItem("Orig+");
        box_4.addItem("Orig-");
        box_4.addItem("V*");
    }
 
    //método que carga datos recibidos
    public void CargarDatos(){
        texto_descripcion.setText(opcion_actual.getDescripcion());
        String[] respuestas = opcion_actual.getNomenclatura().split(",");
        box_1.setSelectedItem(respuestas[0]);
        box_2.setSelectedItem(respuestas[1]);
        box_3.setSelectedItem(respuestas[2]);
        if(respuestas.length!=3){
            box_4.setSelectedItem(respuestas[3]);
        }else{
            box_4.setSelectedItem("");
        }
        
    }
    
    //método que carga guardo datos nuevos
    private boolean Guardar() throws SQLException{
        int guardar;
        SetBox();
        opcion_actual.setDescripcion(texto_descripcion.getText());
        guardar=BDOpciones.insertar(opcion_actual);
        if(guardar!=0){
            return true;
        }
        return false;
    }
    
    //método que actualiza datos si esto es una edición
    private boolean Actualizar() throws SQLException{
        SetBox();
        opcion_actual.setDescripcion(texto_descripcion.getText());
        BDOpciones.actualizar(opcion_actual);
        return true;
    } 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    private void SetBox(){
       String nomenclatura="";
       nomenclatura=(String) box_1.getSelectedItem();
       nomenclatura=nomenclatura+","+(String) box_2.getSelectedItem();
       nomenclatura=nomenclatura+","+(String) box_3.getSelectedItem();
       if(!box_4.getSelectedItem().equals("")){
           nomenclatura=nomenclatura+","+(String) box_4.getSelectedItem();
       }
       opcion_actual.setNomenclatura(nomenclatura);
    
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        texto_descripcion = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        b_cancelar = new javax.swing.JButton();
        box_1 = new javax.swing.JComboBox();
        box_2 = new javax.swing.JComboBox();
        box_3 = new javax.swing.JComboBox();
        box_4 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(81, 106, 138));
        jPanel1.setPreferredSize(new java.awt.Dimension(100, 41));

        jLabel3.setForeground(new java.awt.Color(254, 254, 254));
        jLabel3.setText("Opciones");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jLabel1.setText("Descripción");

        jLabel2.setText("Nomenclatura");

        texto_descripcion.setColumns(20);
        texto_descripcion.setRows(5);
        jScrollPane1.setViewportView(texto_descripcion);

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        b_cancelar.setText("Cancelar");
        b_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cancelarActionPerformed(evt);
            }
        });

        box_1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        box_2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        box_3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        box_4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(b_cancelar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(box_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(box_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(box_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(box_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(box_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(box_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(box_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(box_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(b_cancelar))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        boolean estado = false;
        if(nuevo){
            try {
                estado=Guardar();
            } catch (SQLException ex) {
                Logger.getLogger(D_Opciones.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            try {
                estado=Actualizar();
            } catch (SQLException ex) {
                Logger.getLogger(D_Opciones.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if(estado){
            this.dispose();
        }
        else{
            JOptionPane.showMessageDialog(null, "No se pudo guardar datos");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void b_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_b_cancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(D_Opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(D_Opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(D_Opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(D_Opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Lamina lamina = null;
                D_Opciones dialog = new D_Opciones(new javax.swing.JFrame(), true,lamina);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_cancelar;
    private javax.swing.JComboBox box_1;
    private javax.swing.JComboBox box_2;
    private javax.swing.JComboBox box_3;
    private javax.swing.JComboBox box_4;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea texto_descripcion;
    // End of variables declaration//GEN-END:variables
}
