package Pantallas;

import BaseDeDatos.BDRegistros;
import Entidades.Registro;
import Entidades.Usuario;
import Util.TablaModelo;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.SQLException;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.TableRowSorter;

public class P_Registro extends javax.swing.JInternalFrame {

    public P_Registro() {
        initComponents();
    }

    TablaModelo LRegistros = new TablaModelo();
    TableRowSorter sorter = new TableRowSorter(LRegistros);
    private Registro registro_actual=new Registro();
    boolean seleccion=false;
    java.awt.Frame pantalla_padre;
    
    P_Registro(java.awt.Frame Pantalla_padre) {
        Pantalla_padre=pantalla_padre;
        initComponents();
        tabla_registros.setRowSorter(sorter);
        actualizartabla();
     }
     
    //Metodo que actualiza la tabla de productos
    public void actualizartabla(){
        limpiartabla();
        String titulos[] = {"Codigo","CI","Nombre","Apellido","Descripción","Usuario","Perfil","Grupo","Respuestas"};
        LRegistros.setColumnIdentifiers(titulos);
        try {
            for (Iterator<Registro> it = BDRegistros.Lista() .iterator(); it.hasNext();) {
                Registro registro = it.next();
                String Datos[] = {String.valueOf(registro.getCodigo()),
                                  String.valueOf(registro.getCi()),
                                  registro.getNombre(),
                                  registro.getApellido(),
                                  registro.getDescripcion(),
                                  String.valueOf(registro.getUsuario()),
                                  String.valueOf(registro.getPerfil()),
                                  String.valueOf(registro.getCodigo_grupo())
                                  //RECUPERAR RESPUESTAS
                                  };
                LRegistros.addRow(Datos);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "ERROR: " + e.getMessage());
        }
    }
     
    //Metodo que limpia la tabla de Productos
    public void limpiartabla(){
        int tamaño =LRegistros.getRowCount()-1;
        for(int i=tamaño; i>=0;i--){
              LRegistros.removeRow(i );
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_registros = new javax.swing.JTable();
        b_modificar = new javax.swing.JButton();

        setClosable(true);

        tabla_registros.setModel(LRegistros);
        jScrollPane1.setViewportView(tabla_registros);

        b_modificar.setText("Modificar");
        b_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_modificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(b_modificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b_modificar)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_modificarActionPerformed
        int columna = tabla_registros.getSelectedRow();
        if (columna!=-1){
            try {
                Registro p_envia=new Registro() {};
                Object valor =tabla_registros.getValueAt(columna, 0);
                p_envia=BDRegistros.buscarId(Integer.parseInt(valor.toString()));
                D_Registro editar= new D_Registro(pantalla_padre,true,p_envia);
                editar.setLocationRelativeTo(null);
                editar.setResizable(false);
                editar.setVisible(true);
                //Actualiza tabla despues de cerrar ventana modificar
                editar.addWindowListener(new WindowAdapter() {
                    public void windowClosed(WindowEvent e) {
                        actualizartabla();
                    }
                });
            } catch (SQLException ex) {
                Logger.getLogger(P_Usuario.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Seleccione una fila de la tabla");
        }
    }//GEN-LAST:event_b_modificarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_modificar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla_registros;
    // End of variables declaration//GEN-END:variables
}
